// WHAT IS STRICT EQUALITY (===)?
// >> A COMPARISON OPERATOR THAT CHECKS IF TWO VALUES ARE EQUAL IN BOTH VALUE AND DATA TYPE.
// >> IT PREVENTS TYPE COERCION, ENSURING THAT '10' (STRING) IS NOT CONSIDERED EQUAL TO 10 (NUMBER).

// 1. ASSIGNMENT OPERATOR (=)
// >> USED TO ASSIGN A VALUE TO A VARIABLE.
   let number = 10;

// 2. LOOSE EQUALITY OPERATOR (==)
// >> COMPARES TWO VALUES FOR EQUALITY AFTER PERFORMING TYPE COERCION.
// >> IF THE DATA TYPES ARE DIFFERENT, JAVASCRIPT ATTEMPTS TO CONVERT THEM TO THE SAME TYPE BEFORE COMPARING.
   let number1 = 10;
   let number2 = '10';
   let compareNumber = (number1 == number2) ? 'Yes' : 'No'; 
   console.log(compareNumber); // OUTPUT: 'Yes' (BECAUSE 10 == 10)

// 3. STRICT EQUALITY OPERATOR (===)
// >> COMPARES TWO VALUES WITHOUT TYPE COERCION.
// >> BOTH THE VALUE AND THE DATA TYPE MUST BE IDENTICAL FOR THIS TO RETURN TRUE.
   let number3 = 10;
   let number4 = "10";
   let compare = (number3 === number4) ? 'Yes' : 'No'; 
   console.log(compare); // OUTPUT: 'No' (BECAUSE NUMBER IS NOT A STRING)