// WHAT ARE STRING METHODS?
// >> THESE ARE BUILT-IN JAVASCRIPT FUNCTIONS THAT ALLOW US TO MANIPULATE AND ANALYZE TEXT DATA.
// >> STRING METHODS PROVIDE A TOOLSET TO MODIFY, SEARCH, OR TRANSFORM THE CONTENT OF A STRING.

// EXAMPLE:

let firstName = 'ron jerwin';

console.log(firstName.toUpperCase());      // CONVERTS ALL CHARACTERS IN THE STRING TO UPPERCASE.
console.log(firstName.toLowerCase());      // CONVERTS ALL CHARACTERS IN THE STRING TO LOWERCASE.
console.log(firstName.charAt(5));          // RETURNS THE CHARACTER AT THE SPECIFIED INDEX (STARTING FROM 0).
console.log(firstName.slice(0, 3));        // EXTRACTS A SECTION OF A STRING FROM START INDEX (INCLUSIVE) TO END INDEX (EXCLUSIVE).
console.log(firstName.slice(4));           // EXTRACTS A SECTION OF A STRING FROM THE SPECIFIED INDEX TO THE END.
console.log(firstName.trim());             // REMOVES WHITESPACE FROM BOTH THE BEGINNING AND THE END OF THE STRING.
console.log(firstName.split(" ", 2));      // DIVIDES A STRING INTO AN ARRAY OF SUBSTRINGS BASED ON A SEPARATOR, WITH AN OPTIONAL LIMIT.
console.log(firstName.startsWith('r'));    // CHECKS IF A STRING BEGINS WITH A SPECIFIED VALUE; RETURNS A BOOLEAN.
console.log(firstName.endsWith('n'));      // CHECKS IF A STRING ENDS WITH A SPECIFIED VALUE; RETURNS A BOOLEAN.
console.log(firstName.padStart(15, '-'));  // PADS THE START OF THE STRING WITH A FILLER CHARACTER UNTIL IT REACHES A SPECIFIED LENGTH.
console.log(firstName.padEnd(15, '-'));    // PADS THE END OF THE STRING WITH A FILLER CHARACTER UNTIL IT REACHES A SPECIFIED LENGTH.
console.log(firstName.length);             // RETURNS THE TOTAL NUMBER OF CHARACTERS IN THE STRING.
console.log(firstName.indexOf('j'));       // RETURNS THE INDEX OF THE FIRST OCCURRENCE OF A SPECIFIED CHARACTER.
console.log(firstName.includes('o'));      // CHECKS IF THE STRING CONTAINS A SPECIFIED SUBSTRING; RETURNS A BOOLEAN.
console.log(firstName.replace('ron', 'Ron'));   // REPLACES THE FIRST MATCH OF A PATTERN WITH A REPLACEMENT STRING.
console.log(firstName.replaceAll(' ', '-')); // REPLACES ALL MATCHES OF A PATTERN WITH A REPLACEMENT STRING.
console.log(firstName.lastIndexOf('r'));    // RETURNS THE INDEX OF THE LAST OCCURRENCE OF A SPECIFIED CHARACTER.
console.log(firstName.trimEnd());          // REMOVES WHITESPACE ONLY FROM THE END OF THE STRING.
console.log(firstName.trimStart());        // REMOVES WHITESPACE ONLY FROM THE BEGINNING OF THE STRING.