// WHAT IS TYPE CONVERSION?
// >> TYPE CONVERSION IS A PROCESS OF CONVERTING A VALUE FROM ONE DATA TYPE TO ANOTHER.

// SOMETIMES YOU'LL ENCOUNTER A LOGIC THAT NEEDS A TYPE CONVERSION
// >> EXAMPLE:
  let userInput = window.prompt('Enter a number: ');
  // typeof IS USED IF YOUR WANT TO CHECK WHAT IS THE DATA TYPE OF A VARIABLE.
  // USING WINDOW.PROMPT EVEN WHEN YOU INPUT A NUMBER VALUE, THE TYPE OF IT WILL BE STRING.
  // TO CONVERT THE DATA TYPE OF userInput INTO A NUMBER:
    userInput = Number(userInput);
    console.log(typeof userInput);

  // TO CONVERT A NUMBER DATA TYPE INTO STRING:
    userInput = String(userInput);
    console.log(typeof userInput);

  // TO CONVERT A STRING DATA TYPE INTO BOOLEAN:
    userInput = Boolean(userInput);
    console.log(typeof userInput);

// NOTE: IF YOU HAVE AN INPUT ELEMENT, AND YOU WANT TO PERFORM CALCULATIONS ON NUMBER, YOU CAN YOU TYPE CONVERSION
// BECAUSE BY INPUT ELEMENT BY DEFAULT EVEN IF YOU SET THEIR TYPE="number", IT MEANS YOU CAN ONLY INPUT A NUMBER
// BUT ITS DATA TYPE WILL ALWAY STRING.