// WHAT IS A VARIBLE?
// >> VARIABLE IS A CONTAINER THAT STORES A VALUE/DATA.
// >> IT BEHAVE AS IF IT WERE THE VALUE IT CONTAINS.

// WHAT IS A KEYWORD?
// >> KEYWORD IS USED IN JAVASCRIPT TO DECLARE A VARIABLE
// >> EXAMPLES ARE: let, const, and var

// LET KEYWORD IS USED IF A VALUE NEEDS TO REASSIGN.
// CONST IS USED IF THE VALUE IF FIXED AND CANNOT BE REASSIGNED.
// VAR IS A DEPRICATED KEYWORD THAT HAS A FUNCTION LIKE LET. BUT IT HAS A DOWNSIDE SO PREFERRABLY USE LET INSTEAD OF VAR.

// WHAT IS IDENTIFIER?
// >> INDENTIFIER IS THE NAME THAT YOU GIVE TO YOUR VARIABLE. 
// >> NOTE: USE A PROPER NAMING CONVENTION WHEN CREATING A VARIABLE. THIS WOULD MAKE THE PRODUCTION MUCH FASTER AND MAINTAINABLE.

// WHAT IS A VALUE?
// >> A VALUE IS THE DATA THAT YOU ASSIGN TO A VARIABLE AS ITS VALUE.

// HOW TO DECLARE A VARIABLE?
// SYNTAX: keyword identifier = value;
  let greet1 = 'Hello, User!'; // VARIABLE DECLARATION USING LET.
//                               THIS IS USED IF YOU WANT TO REASSIGN A VALUE OF YOUR VARIABLE.

  const greet2 = 'Hello, User!'; // VARIABLE DECLARATION USING CONST.
//                                  IF YOU USED CONST, YOU CANNOT REASSIGN A VALUE OF YOUR VARIABLE.
