// WHAT IS AN ARRAY?
// >> A SPECIAL VARIABLE THAT CAN HOLD MORE THAN ONE VALUE AT A TIME UNDER A SINGLE NAME.
// >> ARRAYS ARE ORDERED COLLECTIONS, MEANING EACH ITEM HAS A NUMERIC INDEX STARTING AT 0.

// EXAMPLE:
// ARRAYS CAN STORE MIXED DATA TYPES (STRINGS, NUMBERS, BOOLEANS, OBJECTS).
const fruits = ['BANANA', 5, TRUE, { NAME: 'RJ' }];

// ESSENTIAL ARRAY METHODS:
fruits.push('APPLE');      // ADDS AN ELEMENT TO THE END.
fruits.pop();              // REMOVES THE LAST ELEMENT.
fruits.unshift('ONION');   // ADDS AN ELEMENT TO THE BEGINNING (SHIFTING OTHERS TO THE RIGHT).
fruits.shift();            // REMOVES THE FIRST ELEMENT (SHIFTING OTHERS TO THE LEFT).
fruits.sort();             // SORTS ELEMENTS ALPHABETICALLY (NOTE: BE CAREFUL WITH NUMBERS!).
fruits.reverse();          // REVERSES THE ORDER OF ELEMENTS.