// WHAT IS A WHILE LOOP?
// >> A CONTROL FLOW STATEMENT THAT REPEATEDLY EXECUTES A BLOCK OF CODE AS LONG AS THE SPECIFIED CONDITION REMAINS TRUE.
// >> THE CONDITION IS EVALUATED BEFORE EACH ITERATION.

// EXAMPLE OF WHILE LOOP:
let count = 10;
let startCount = 0;

while (startCount <= count) {
    console.log(startCount);
    startCount++; // INCREMENT TO AVOID AN INFINITE LOOP
}

// WHAT IS A DO...WHILE LOOP?
// >> SIMILAR TO A WHILE LOOP, BUT IT GUARANTEES THAT THE CODE BLOCK EXECUTES AT LEAST ONCE.
// >> THE CONDITION IS EVALUATED AFTER THE CODE EXECUTION.

// EXAMPLE OF DO...WHILE LOOP:
do {
    console.log(startCount);
    startCount++;
} while (startCount <= count);