// WHAT IS JAVASCRIPT?
// >> JAVASCRIPT IS THE PROGRAMMING LANGUANGE OF THE WEB.
// >> IT IS USED TO ADD INTERACTIVITY TO ALL ELEMENTS OF A WEBPAGE.


// HOW TO OUTPUT A VALUE IN THE CONSOLE?
  console.log('Hello, World!'); // CONSOLE OUTPUT: 'Hello, World!';

// IF YOU WANT TO CREATE A POP-UP IN YOUR WEBPAGE:
  alert('Hello, World!');
  // >> THIS WILL POP-UP AN ALERT DIAGLOG IN YOUR WEBPAGE SAYING 'Hello, World!'.

// TO CREATE A WINDOW PROPMT POP-UP TO THE WEBPAGE:
  window.prompt('What is your name?: ');
  // >> THIS WILL POP-UP A WINDOW PROMPT ASKING 'What is your name?'.
  