// WHAT IS ES6 MODULE?
// >> IT IS AN EXTERNAL FILE THAT CONTAINS A RAUSABLE CODE THAT CAN BE IMPORTED INTO ANOTHER JAVASCRIPT FILE.
// >> ES6 MODULES CONTAINS VARABLES, FUNCTION, CLASS, OBJECTS.... AND MORE
// >> INTRODUCED ASPART OF ECMASCRIPT 2015 UPDATE.

import { nameOrganizer } from './nameOrganizer.js';

console.log(nameOrganizer('rOnJeWiN'));