// WHAT IS ARITHMETIC OPERATORS
// >> IT IS USED TO PERFORM MATHEMATICAL OPERATIONS/CALCULATIONS IN JAVASCRIPT.
// >> VARIABLE AND VALUE ARE CALLED: OPERAND
// >> WHILE SYMBOLS LIKE (+, -, /, *, %, **) ARE CALLED: OPERATORS.

// IN JAVASCRIPT IT HAS A THREE TYPE TO DECLARE A ARITHMETIC OPERATORS.

// 1.) NORMAL SIGNING OPERATOR || DEFAULT ASSIGNMENT OPERATOR.
// >> IT IS THE DEFAULT USE TO PERFOM CALCULATIONS.
// EXAMPLE:
  let num1 = 10;

  num1 = num1 + 5; // USED TO SUM A VALUE.
  num1 = num1 - 5; // USED TO SUBTRACT A VALUE.
  num1 = num1 / 5; // USED TO DIVIDE A VALUE.
  num1 = num1 * 5; // USED TO MULTIPLY A VALUE.
  num1 = num1 % 5; // USED TO GET THE REMAINDER.
  num1 = num1 ** 5; // USED TO GET THE EXPONENTIAL.


// 2.) AUGMENTED ASSIGNMENT OPERATOR || SHORT-HAND SIGNING OPERATOR.
// >> IT IS USED AS THE SHORT-HAND OR SHORTCUT ALTERNATIVE WAY OF USING DEFAULT CALCULATION.
// EXAMPE:
  let num2 = 10;

  num2 += 5; // USED TO SUM A VALUE.
  num2 -= 5; // USED TO SUBTRACT A VALUE.
  num2 /= 5; // USED TO DIVIDE A VALUE.
  num2 *= 5; // USED TO MULTIPLY A VALUE.
  num2 %= 5; // USED TO GET THE REMAINDER.
  num2 **= 5; // USED TO GET THE EXPONENTIAL.


// 3.) INCREMENTATION && DECREMENTATION
// >> THIS IS USED IF YOU WANT YOUR CALCULATION INCREMENT OR DECREMENT BY 1.
// EXAMPLE:
  let num3 = 10;

  num3++; // USED TO INCREMENT A VALUE BY 1.
  num3--; // USED TO DECREMENT A VALUE BY 1.


// IMPORTANT!!

// JAVASCRIPT ARITHMETIC OPERATION HAS A IMPORTANT PROCESS OF CALCULATING A VALUE MOSTLY IN A NESTED OPERATORS IN A SINGLE LINE OF CODE.
// >> IT IS CALLED OPERATOR PRECEDENCE.

// OPERATOR PRECEDENCE IS A PROCESS OF JAVASCRIPT TO DEFINE WHAT OPERATOR WILL EXECUTE FIRST IF WE HAVE A MULTIPLE OPERATORS IN A SINGLE LINE OF CODE.

// >> OPERATOR PRECEDENCE:
  // 1.) PARENTHESIS ()
  // 2.) EXPONENTIAL **
  // 3.) MULTIPLICATION, DIVISION, AND MODULO (*, /, %)
  // 4.) ADDITION, SUBTRACTION (+, -)

// EXAMPLE:


let calculation = 5 ** 2 + 5 * (4 - 1); 
//                 2nd  4th 3rd  1st
//                                3
//                 25
//                           15
//                       40 
//                OUTPUT WILL BE: 40.