// WHAT IS VARIABLE SCOPE?
// >> SCOPE DEFINES THE ACCESSIBILITY (VISIBILITY) OF VARIABLES. IT DETERMINES WHERE IN YOUR CODE A VARIABLE CAN BE READ OR MODIFIED.

// 1. GLOBAL SCOPE
// >> VARIABLES DECLARED OUTSIDE OF ANY FUNCTION OR BLOCK. 
// >> THEY ARE ACCESSIBLE FROM ANYWHERE WITHIN THE FILE OR SCRIPT.
let globalResult = 0; 

// 2. LOCAL (FUNCTION) SCOPE
// >> VARIABLES DECLARED INSIDE A FUNCTION. 
// >> THEY ARE ONLY ACCESSIBLE WITHIN THAT SPECIFIC FUNCTION.
function sum(num1, num2) {
    let localSum = num1 + num2; // 'localSum' CANNOT BE ACCESSED OUTSIDE THIS FUNCTION.
    console.log(localSum);
}

// 3. SHADOWING (PRIORITY)
// >> IF A LOCAL VARIABLE HAS THE SAME NAME AS A GLOBAL VARIABLE, THE LOCAL VARIABLE "SHADOWS" (TAKES PRIORITY OVER) THE GLOBAL ONE INSIDE THAT SCOPE.
let result = 100; // GLOBAL

function multiply(num1, num2) {
    let result = num1 * num2; // THIS 'result' ONLY EXISTS INSIDE THIS FUNCTION.
    console.log(result); // OUTPUTS THE LOCAL RESULT
}

multiply(5, 5); // OUTPUTS 25
console.log(result); // OUTPUTS 100 (THE GLOBAL VARIABLE REMAINS UNCHANGED)