// WHAT IS TERNARY OPERATOR?
// >> TERNARY OPERATOR IS USED AS A ALTERNATIVE WAY TO MAKE A SHORT IF STATEMENT.
// >> TERNARY OPERATOR (?) IS USED TO MAKE A CONDITION INSIDE OF A VARIABLE.

// STEP BY STEP SYNTAX OF USING TERNARY OPERATOR:
// LOGIC: (CONDITION) ? (RESULT IF TRUE) : (RESULT IF FALSE)

// EXAMPLE:

// THIS IS A SHORT IF ELSE STATEMENT

let age = 13;

  if(age >= 13) {
    console.log("You're a TEEN!");
  } else {
    console.log("You're a CHILD!");
  }
  console.log(age);

// THIS IS A TERNARY OPERATOR

let ageLabel = age >= 13 ? "You're a TEEN!" : "You're a CHILD!";
console.log(ageLabel);
// EVALUATES THE CONDITION: RETURNS THE FIRST EXPRESSION IF TRUE, THE SECOND IF FALSE.
