// WHAT IS A CLASS?
// >> (ES6 FEATURE) PROVIDES A MORE STRUCTURED AND CLEANER WAY TO WORK WITH OBJECTS COMPARED TO TRADITIONAL CONSTRUCTOR FUNCTION.
// >> IT HAS A BUILT-IN CONSTRUCTOR.
// DEFINING A CLASS ACTS AS A BLUEPRINT FOR CREATING OBJECTS.
// IT GROUPS DATA (PROPERTIES) AND BEHAVIOR (METHODS) TOGETHER.

class Product {
  
  // THE CONSTRUCTOR IS A SPECIAL METHOD THAT RUNS AUTOMATICALLY
  // WHENEVER A NEW INSTANCE OF THE CLASS IS CREATED.
  // IT IS USED TO INITIALIZE THE OBJECT'S STARTING PROPERTIES.
  constructor(name, price) {
    this.name = name;   // ASSIGN THE PROVIDED NAME TO THE OBJECT
    this.price = price; // ASSIGN THE PROVIDED PRICE TO THE OBJECT
  }

  // METHODS DEFINED INSIDE THE CLASS ARE SHARED BY ALL INSTANCES.
  // THIS METHOD DISPLAYS THE CURRENT PRODUCT'S DETAILS IN THE CONSOLE.
  displayProduct() {
    console.log(`Product: ${this.name}`);
    console.log(`Price: $${this.price}`);
  }

  // THIS METHOD PERFORMS A CALCULATION USING THE OBJECT'S DATA.
  // IT TAKES A 'salesTax' PARAMETER TO COMPUTE THE TOTAL PRICE.
  calculateTax(salesTax) {
    return this.price + (this.price * salesTax);
  }
}

// CREATING A NEW INSTANCE (OBJECT) CALLED 'product1'
// BASED ON THE 'Product' BLUEPRINT.
const product1 = new Product('Monitor', 59.99);

// CALLING THE METHODS DEFINED WITHIN THE CLASS TO INTERACT
// WITH THE DATA STORED INSIDE THE 'product1' OBJECT.
product1.displayProduct();
console.log(`Total with Tax: $${product1.calculateTax(0.1).toFixed(2)}`);